# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContactFile(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1080, 700)
        Widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.logo = QtWidgets.QLabel(Widget)
        self.logo.setGeometry(QtCore.QRect(430, 40, 221, 221))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("D:\\NARUTO\\gui\\uzumkai logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.name = QtWidgets.QLabel(Widget)
        self.name.setGeometry(QtCore.QRect(130, 300, 231, 91))
        self.name.setStyleSheet("border-image: url(D:/NARUTO AI/GUI KEYS/CONTACT/NAME.png);")
        self.name.setText("")
        self.name.setObjectName("name")
        self.number = QtWidgets.QLabel(Widget)
        self.number.setGeometry(QtCore.QRect(80, 430, 271, 121))
        self.number.setStyleSheet("border-image: url(D:/NARUTO AI/GUI KEYS/CONTACT/NUMBER.png);")
        self.number.setText("")
        self.number.setObjectName("number")
        self.savebutton = QtWidgets.QPushButton(Widget)
        self.savebutton.setGeometry(QtCore.QRect(390, 570, 211, 81))
        self.savebutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.savebutton.setStyleSheet("border-image: url(D:/NARUTO AI/GUI KEYS/CONTACT/save.png);\n"
"background-color: transparent;")
        self.savebutton.setText("")
        self.savebutton.setObjectName("savebutton")
        self.cancelbutton = QtWidgets.QPushButton(Widget)
        self.cancelbutton.setGeometry(QtCore.QRect(710, 560, 221, 101))
        self.cancelbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelbutton.setMouseTracking(False)
        self.cancelbutton.setStyleSheet("border-image: url(D:/NARUTO AI/GUI KEYS/CONTACT/cancel.png);\n"
"background-color: transparent;")
        self.cancelbutton.setText("")
        self.cancelbutton.setObjectName("cancelbutton")
        self.frame = QtWidgets.QFrame(Widget)
        self.frame.setGeometry(QtCore.QRect(60, 20, 951, 651))
        self.frame.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"border-radius:50px;\n"
"border-width:5px 5px 5px 5px;\n"
"border-style:solid;\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.nameline = QtWidgets.QLineEdit(self.frame)
        self.nameline.setGeometry(QtCore.QRect(330, 280, 541, 91))
        self.nameline.setStyleSheet("font: 36pt \"Vermin Vibes\";\n"
"padding-left:10px;color:rgb(255,255,255)\n"
"")
        self.nameline.setObjectName("nameline")
        self.numberline = QtWidgets.QLineEdit(self.frame)
        self.numberline.setGeometry(QtCore.QRect(330, 430, 541, 91))
        font = QtGui.QFont()
        font.setFamily("Vermin Vibes")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        self.numberline.setFont(font)
        self.numberline.setStyleSheet("font: 36pt \"Vermin Vibes\";\n"
"padding-left:10px;color:rgb(255,255,255)\n"
"")
        self.numberline.setObjectName("numberline")
        self.frame.raise_()
        self.logo.raise_()
        self.name.raise_()
        self.number.raise_()
        self.savebutton.raise_()
        self.cancelbutton.raise_()

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.nameline.setPlaceholderText(_translate("Widget", "entername"))
        self.numberline.setPlaceholderText(_translate("Widget", "enternumber"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ContactsFile = QtWidgets.QWidget()
    ui = Ui_ContactFile()
    ui.setupUi(ContactsFile)
    ContactsFile.show()
    sys.exit(app.exec_())
