# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindowClass(object):
    def setupUi(self, loginWindowClass):
        loginWindowClass.setObjectName("loginWindowClass")
        loginWindowClass.resize(1080, 720)
        loginWindowClass.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.logo = QtWidgets.QLabel(loginWindowClass)
        self.logo.setGeometry(QtCore.QRect(150, 200, 221, 211))
        self.logo.setStyleSheet("border-image: url(D:/NARUTO AI/QT/loginWindowClass/GUI KEYS/uzumkai logo.png);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.frame = QtWidgets.QFrame(loginWindowClass)
        self.frame.setGeometry(QtCore.QRect(520, 80, 511, 561))
        self.frame.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);\n"
"border-radius:30px;\n"
"border-width:10px 10px 10px 10px;\n"
"border-style:solid;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.username = QtWidgets.QLineEdit(self.frame)
        self.username.setGeometry(QtCore.QRect(60, 80, 381, 111))
        self.username.setStyleSheet("font: 43pt \"Vermin Vibes\";\n"
"padding-left:15px;")
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(60, 270, 381, 111))
        self.password.setStyleSheet("font: 43pt \"Vermin Vibes\";\n"
"padding-left:15px;")
        self.password.setText("")
        self.password.setObjectName("password")
        self.exitbutton = QtWidgets.QPushButton(self.frame)
        self.exitbutton.setGeometry(QtCore.QRect(270, 410, 211, 151))
        self.exitbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitbutton.setStyleSheet("border-image: url(D:/NARUTO AI/QT/loginWindowClass/GUI KEYS/exit2.png);\n"
"background-color: transparent;")
        self.exitbutton.setText("")
        self.exitbutton.setObjectName("exitbutton")
        self.retrybutton = QtWidgets.QPushButton(self.frame)
        self.retrybutton.setGeometry(QtCore.QRect(50, 410, 181, 131))
        self.retrybutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.retrybutton.setStyleSheet("border-image: url(D:/NARUTO AI/QT/loginWindowClass/GUI KEYS/retry-1.png);\n"
"background-color: transparent;")
        self.retrybutton.setText("")
        self.retrybutton.setObjectName("retrybutton")
        self.accessdenied = QtWidgets.QLabel(self.frame)
        self.accessdenied.setGeometry(QtCore.QRect(40, 20, 421, 411))
        self.accessdenied.setStyleSheet("border:none;\n"
"")
        self.accessdenied.setText("")
        self.accessdenied.setPixmap(QtGui.QPixmap("D:\\NARUTO AI\\QT\\loginWindowClass\\GUI KEYS\\ACCDSS DEN.gif"))
        self.accessdenied.setScaledContents(True)
        self.accessdenied.setObjectName("accessdenied")
        self.loginbutton = QtWidgets.QPushButton(loginWindowClass)
        self.loginbutton.setGeometry(QtCore.QRect(170, 430, 181, 131))
        self.loginbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginbutton.setStyleSheet("border-image: url(D:/NARUTO AI/QT/loginWindowClass/GUI KEYS/login.png);\n"
"background-color: transparent;")
        self.loginbutton.setText("")
        self.loginbutton.setObjectName("loginbutton")

        self.retranslateUi(loginWindowClass)
        QtCore.QMetaObject.connectSlotsByName(loginWindowClass)

    def retranslateUi(self, loginWindowClass):
        _translate = QtCore.QCoreApplication.translate
        loginWindowClass.setWindowTitle(_translate("loginWindowClass", "loginWindowClass"))
        self.username.setPlaceholderText(_translate("loginWindowClass", "USERNAME"))
        self.password.setPlaceholderText(_translate("loginWindowClass", "PASSWORD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginWindowClass = QtWidgets.QWidget()
    ui = Ui_loginWindowClass()
    ui.setupUi(loginWindowClass)
    loginWindowClass.show()
    sys.exit(app.exec_())
