# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 550)
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.uzumakilogo = QtWidgets.QLabel(Dialog)
        self.uzumakilogo.setGeometry(QtCore.QRect(170, 60, 341, 341))
        self.uzumakilogo.setText("")
        self.uzumakilogo.setPixmap(QtGui.QPixmap("D:\\NARUTO AI\\LOGO\\uzumkai logo.gif"))
        self.uzumakilogo.setScaledContents(True)
        self.uzumakilogo.setObjectName("uzumakilogo")
        self.loginbutton = QtWidgets.QPushButton(Dialog)
        self.loginbutton.setGeometry(QtCore.QRect(120, 430, 171, 111))
        self.loginbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loginbutton.setStyleSheet("border-image: url(D:/NARUTO AI/QT/mainfile/GUI KEYS/login.png);\n"
"background-color: transparent;")
        self.loginbutton.setText("")
        self.loginbutton.setObjectName("loginbutton")
        self.exitbutton = QtWidgets.QPushButton(Dialog)
        self.exitbutton.setGeometry(QtCore.QRect(410, 430, 181, 111))
        self.exitbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitbutton.setStyleSheet("border-image: url(D:/NARUTO AI/QT/mainfile/GUI KEYS/exit.png);\n"
"background-color: transparent;")
        self.exitbutton.setText("")
        self.exitbutton.setObjectName("exitbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
